name: Build macOS Executable

on:
  push:
    branches:
      - master
  workflow_dispatch: # Pozwala ręcznie wyzwalać workflow

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Pobranie kodu źródłowego
      - name: Checkout code
        uses: actions/checkout@v3

      # Ustawienie środowiska Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Instalacja systemowych zależności
      - name: Install system dependencies
        run: |
          brew install tcl-tk
          brew install portaudio
          brew install ninja meson

      # Instalacja zależności Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pyinstaller
          pip install -r requirements.txt

      # Tworzenie pliku wykonywalnego
      - name: Build executable
        run: |
          pyinstaller --onefile --windowed TinPop.py

      # Przesłanie artefaktu (pliku wykonywalnego)
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: TinPop-macOS
          path: dist/TinPop
